name: Build luasocket for Win32 static

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout luasocket
        uses: actions/checkout@v4
        with:
          repository: fiendish/luasocket
          path: luasocket
          submodules: recursive

      - name: Checkout LuaJIT
        uses: actions/checkout@v4
        with:
          repository: fiendish/LuaJIT
          ref: v2.1
          path: luasocket/LuaJIT
          submodules: recursive

      - name: Download prebuilt lua51.lib
        working-directory: luasocket
        run: |
          Invoke-WebRequest 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.lib' -OutFile 'lua51.lib'

      - name: Set up MSVC x86 build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build luasocket
        working-directory: luasocket
        run: |
          # Debug: Check if LuaJIT headers exist
          Write-Host "Checking LuaJIT headers..."
          Get-ChildItem "LuaJIT\src\*.h" | Select-Object Name
          
          # Build using MSBuild with paths passed directly as properties
          $luaIncPath = (Resolve-Path "LuaJIT\src").Path
          $luaLibPath = (Resolve-Path ".").Path
          Write-Host "LUAINC: $luaIncPath"
          Write-Host "LUALIB: $luaLibPath"
          
          msbuild luasocket.sln /p:PlatformToolset=v143 /p:Configuration=Release /p:Platform=Win32 /p:RuntimeLibrary=MultiThreaded /p:LUAINC="$luaIncPath" /p:LUALIB="$luaLibPath" /p:LUALIBNAME="lua51.lib"
          
      - name: Create directory structure
        working-directory: luasocket
        run: |
          # Create directories
          New-Item -ItemType Directory -Path "lua" -Force
          New-Item -ItemType Directory -Path "socket" -Force
          New-Item -ItemType Directory -Path "mime" -Force
          
          # Move socket.lua and ltn12.lua to lua folder
          Move-Item "src\socket.lua" "lua\socket.lua" -Force
          Move-Item "src\ltn12.lua" "lua\ltn12.lua" -Force
          
          # Move socket core.dll and remaining .lua files to socket folder
          Move-Item "Release\socket\core.dll" "socket\core.dll" -Force
          Move-Item "src\*.lua" "socket\" -Force
          
          # Move mime core.dll to mime folder
          Move-Item "Release\mime\core.dll" "mime\core.dll" -Force

      - name: Create release package
        working-directory: luasocket
        run: |
          # Create zip archive with the organized directory structure
          Compress-Archive -Path "lua", "socket", "mime" -DestinationPath "luasocket-win32-static.zip" -Force

      - name: Create or update "latest" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: luasocket/luasocket-win32-static.zip
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
