name: Build luasocket for Win32 static

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout luasocket
        uses: actions/checkout@v4
        with:
          repository: fiendish/luasocket
          path: luasocket
          submodules: recursive

      - name: Checkout LuaJIT
        uses: actions/checkout@v4
        with:
          repository: fiendish/LuaJIT
          ref: v2.1
          path: luasocket/LuaJIT
          submodules: recursive

      - name: Download prebuilt lua51.lib
        working-directory: luasocket
        run: |
          Invoke-WebRequest 'https://github.com/fiendish/LuaJIT-build/releases/download/latest/lua51.lib' -OutFile 'lua51.lib'

      - name: Set up MSVC x86 build environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build luasocket
        working-directory: luasocket
        run: |
          # Build using the makefile with win32 platform and LuaJIT, using static runtime
          nmake -f src/makefile PLAT=win32 LUAV=5.1 LUAPREFIX_win32=..\luajit LUAINC_win32=..\LuaJIT\src LUALIB_win32=..\lua51.lib CC_win32="cl /MT /O1 /Os /DWIN32 /DNDEBUG /D_WINDOWS /D_USRDLL"
          
          # Copy built DLLs to expected locations (flexible versioning)
          Copy-Item "src\socket-*.dll" "core.dll" -Force
          Copy-Item "src\mime-*.dll" "mime.dll" -Force

      - name: Create directory structure
        working-directory: luasocket
        run: |
          # Create directories
          New-Item -ItemType Directory -Path "lua" -Force
          New-Item -ItemType Directory -Path "socket" -Force
          New-Item -ItemType Directory -Path "mime" -Force
          
          # Move socket.lua and ltn12.lua to lua folder
          Move-Item "src\socket.lua" "lua\socket.lua" -Force
          Move-Item "src\ltn12.lua" "lua\ltn12.lua" -Force
          
          # Move core.dll and remaining .lua files to socket folder
          Move-Item "core.dll" "socket\core.dll" -Force
          Move-Item "src\*.lua" "socket\" -Force
          
          # Move mime.dll to mime folder as core.dll
          Move-Item "mime.dll" "mime\core.dll" -Force

      - name: Create release package
        working-directory: luasocket
        run: |
          # Create zip archive with the organized directory structure
          Compress-Archive -Path "lua", "socket", "mime" -DestinationPath "luasocket-win32-static.zip" -Force

      - name: Create or update "latest" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          files: luasocket/luasocket-win32-static.zip
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
